"""
Constants used inside tests.

.. moduleauthor:: Harvey Lelliott (flip-dots) <harveylelliott@duck.com>
"""

from bleak import BLEDevice

from SolixBLE import const, prime_device

MOCK_DEVICE_NAME = "Mock Device"
"""
Mock device name used to emulate Anker devices for tests.
"""

MOCK_DEVICE_ADDRESS = "AA:BB:CC:DD:EE:FF"
"""
Mock bluetooth address used to emulate Anker devices for tests.
"""

MOCK_BLE_DEVICE = BLEDevice(
    address=MOCK_DEVICE_ADDRESS, name=MOCK_DEVICE_NAME, details={}, rssi=-1
)
"""
Mock BLEDevice used to emulate Anker devices for tests.
"""

SOLIX_TEST_PRIVATE_KEY = "7dfbea61cd95cee49c458ad7419e817f1ade9a66136de3c7d5787af1458e39f4"
"""
ECDH private key the Solix negotiation vectors below were captured with. The
library generates a fresh key per negotiation; tests pin this one so the
recorded frames still match.
"""

PRIME_TEST_PRIVATE_KEY = "754744d72984c378bc4fa77d7fcdf6bbb6d9df119fa9be4948eb8a3b4cd6071f"
"""
ECDH private key the Prime negotiation vectors below were captured with.
"""


NEGOTIATION_RESPONSES_PRIME: dict[str, list[str]] = {
    "ff09200003000140010a82d0ab535303e3aa9f0c2f9c868465bc8476f556fb7d": [
        "ff091e000300014801ab273ed3e27270c3f4d676ac7d69a00572793732a6"
    ],
    "ff09270003000140030a82d0ab53538ab3de100ac9bb87a0b8e36c1dd8167a9c25a9839d9a14d5": [
        "ff092b000300014803ab273ed0443800b35db54c6d4a6ec3d48171a04ea7ebce8bf749e5e48c5d991a5e67"
    ],
    "ff09200003000140290a82d0ab535303e3aa9f0c2f9c868465bc8476f556fb55": [
        "ff0958000300014829ab273ed144326ada9fc66fa02508c5ddf549ade014d1eeb252fea1057c15b00985ab8a724fa3830e8e5b27acbaa1224fd2172c0439d27aaf9e62a66bda5c41c424f23c5c8d7df8d3b89422ddff2266"
    ],
    "ff092d0003000140050a82d0ab53538ab3de100ae04aca6791257881a90164eac7460450e0c82f2c03de4f9604": [
        "ff091b000300014805abab709a595a803dd04246b78a927453cf65"
    ],
    "ff095c0003000140210ac6ea31e4300bb2877d6ddeb628b0d7be8d768333f00ceab5454d20fbd97e091457b1f3b6efb6511eb9e98ac2b2c46eee211ae359ad246e1ae9886b4a29e41eddd5a5064d8b9ffdbfb43eb6b8e307fcde9de7": [
        "ff095d000300014821ab277fc01de436d341de628c79c1384d0aea25ce030622fa3ca0808ce5d1b7365ec1b1753a11ab78fba3ca07dda95cd57c93d1267b1222bef9908f7633a758ab924eba63ee01e715be5b9c3b082e6d81c2204241"
    ],
    # These packets below are dynamically generated by the library unlike previous
    # negotiation packets as past stage 5 negotiations the packets use the shared
    # secret for encryption which is different from device to device due to different
    # public keys. This is why constants are not used. But we can use constants for
    # the earlier packets which use static keys.
    "ff094000030001402257ec76586f3500c8f858e0ba047f237f4e2ed8c50d2f39ba3587e4010275bea22242936f08784271e19d67a6275ff6bb50577acec0a068": [
        "ff091b000300014822f60b45600839b2c171b33dc5790ed64ae32d"
    ],
    "ff094600030001402757ec76586f3501e8cf6185d8c4035707377af9af3a2e40b02b86e7531974f1c22440de6e43705566b77cf940280d70e86b1fa915ab5a360040237091b9": [
        "ff091b000300014827f60b45600839b2c171b33dc5790ed64ae328"
    ],
    "ff09230003000f420057e9b8dfdeb3da799151684e584bb99eaaccfac9baf7cbcfa6e4": [],
    "ff09530003000f420a57e9b883d958e48e5b7de48d980206577e2dafbb3d604dea3686f3011969f0db2311906d142b5730ee2bfb11e3fbbe7485aac887798a31066997edf60c074ea9e1d5351970e9fa5a2960": [],
}
"""
This maps the expected commands sent by the library to what my Anker Prime 160w
charger sends in response. Its used to emulate it for testing negotiations.
"""


NEGOTIATION_RESPONSES_SOLIX: dict[str, list[str]] = {
    const.NEGOTIATION_COMMAND_0: ["ff090e00030001080100a1010152"],
    const.NEGOTIATION_COMMAND_1: [
        "ff091b00030001080300a10102a202fd00a30144a40101a50102ff"
    ],
    const.NEGOTIATION_COMMAND_2: [
        "ff093800030001082900a10103a2054553503332a307302e302e302e33a41041504339464530453237333030323735a506f49d8a104e0c9a"
    ],
    const.NEGOTIATION_COMMAND_3: ["ff090b00030001080500f2"],
    const.NEGOTIATION_COMMAND_4: [
        "ff094d00030001082100a140b2ade5cac4f4a0c1307e44a0e9c5363cb21e4c8485ee324c23be949fa5d5929a75e57da3207c948a0c366ca9ea1ab2cb8e57d2d046a6ebefe5d96adb5d4cb35039"
    ],
    # The command sent to the device in response to entering stage 5
    # is encrypted using the shared secret
    "ff095a00030001402222c97d5c5bf02e0b43c62c864817cd38b9fd152113728513cc88bc4a1b4de3062473fcd5819618c4b926694d2732c337095a18974243127aa5e266f76f9ac7de06ba357763abe88aaef98f8c7a5e48a324": [],
}
"""
This maps the expected commands sent by the library to what my Anker Solix C1000(X)
sends in response. Its used to emulate it for testing negotiations.
"""