"""
Constants used inside tests.

.. moduleauthor:: Harvey Lelliott (flip-dots) <harveylelliott@duck.com>
"""

from bleak import BLEDevice

SOLIX_TEST_PRIVATE_KEY = "7dfbea61cd95cee49c458ad7419e817f1ade9a66136de3c7d5787af1458e39f4"
"""
P-256 private value pinned as the ECDH key of Solix devices in tests.
"""

PRIME_TEST_PRIVATE_KEY = "754744d72984c378bc4fa77d7fcdf6bbb6d9df119fa9be4948eb8a3b4cd6071f"
"""
P-256 private value pinned as the ECDH key of Prime devices in tests.
"""

NEGOTIATION_COMMAND_0 = "ff0936000300010001a10442ad8c69a22462326463306231372d623735642d346162662d626136652d656337633939376332336537b9"
"""
Negotiation opening (0001) sent by a Solix device in tests.
"""

NEGOTIATION_COMMAND_1 = "ff093d000300010003a10442ad8c69a22462326463306231372d623735642d346162662d626136652d656337633939376332336537a30120a40200f064"
"""
Response to 0801 sent by a Solix device in tests.
"""

NEGOTIATION_COMMAND_2 = "ff0936000300010029a10442ad8c69a22462326463306231372d623735642d346162662d626136652d65633763393937633233653791"
"""
Response to 0803 sent by a Solix device in tests.
"""

NEGOTIATION_COMMAND_3 = "ff0940000300010005a10442ad8c69a22462326463306231372d623735642d346162662d626136652d656337633939376332336537a30120a40200f0a50140fb"
"""
Response to 0829 sent by a Solix device in tests.
"""

NEGOTIATION_COMMAND_4 = "ff094c000300010021a140060ea168f232aedb37fb2d120c49180329ac72ab5ec3eb8fd30a2f252dc5e151dabccd9b1dc1e288704ca760a0d8c918e5c94823a1f609a4bf07fb4c33ee219085"
"""
Response to 0805 (the client's public key) sent by a Solix device in tests.
"""

SOLIX_NEGOTIATION_4022 = "ff095a00030001402222c97d5c5bf02e0b43c62c864817cd38b9fd152113728513cc88bc4a1b4de3060868d9deacb562ca59a369397627effb179b08be8ba760943b24407712c55e6bb59f3ae7c142a726d0f46a149eeaded44b"
"""
Response to 0821 sent by a Solix device in tests: ``a1`` time, ``a2`` client
id, ``a3`` UTC offset (int32 seconds west), ``a5`` POSIX time zone. Derived
from the recorded 0821 and the pinned key, not recorded.
"""

MOCK_DEVICE_NAME = "Mock Device"
"""
Mock device name used to emulate Anker devices for tests.
"""

MOCK_DEVICE_ADDRESS = "AA:BB:CC:DD:EE:FF"
"""
Mock bluetooth address used to emulate Anker devices for tests.
"""

MOCK_BLE_DEVICE = BLEDevice(
    address=MOCK_DEVICE_ADDRESS, name=MOCK_DEVICE_NAME, details={}, rssi=-1
)
"""
Mock BLEDevice used to emulate Anker devices for tests.
"""


NEGOTIATION_RESPONSES_PRIME: dict[str, list[str]] = {
    "ff09200003000140010a82d0ab535303e3aa9f0c2f9c868465bc8476f556fb7d": [
        "ff091e000300014801ab273ed3e27270c3f4d676ac7d69a00572793732a6"
    ],
    "ff09270003000140030a82d0ab53538ab3de100ac9bb87a0b8e36c1dd8167a9c25a9839d9a14d5": [
        "ff092b000300014803ab273ed0443800b35db54c6d4a6ec3d48171a04ea7ebce8bf749e5e48c5d991a5e67"
    ],
    "ff09200003000140290a82d0ab535303e3aa9f0c2f9c868465bc8476f556fb55": [
        "ff0958000300014829ab273ed144326ada9fc66fa02508c5ddf549ade014d1eeb252fea1057c15b00985ab8a724fa3830e8e5b27acbaa1224fd2172c0439d27aaf9e62a66bda5c41c424f23c5c8d7df8d3b89422ddff2266"
    ],
    "ff092d0003000140050a82d0ab53538ab3de100ae04aca6791257881a90164eac7460450e0c82f2c03de4f9604": [
        "ff091b000300014805abab709a595a803dd04246b78a927453cf65"
    ],
    "ff095c0003000140210ac6ea31e4300bb2877d6ddeb628b0d7be8d768333f00ceab5454d20fbd97e091457b1f3b6efb6511eb9e98ac2b2c46eee211ae359ad246e1ae9886b4a29e41eddd5a5064d8b9ffdbfb43eb6b8e307fcde9de7": [
        "ff095d000300014821ab277fc01de436d341de628c79c1384d0aea25ce030622fa3ca0808ce5d1b7365ec1b1753a11ab78fba3ca07dda95cd57c93d1267b1222bef9908f7633a758ab924eba63ee01e715be5b9c3b082e6d81c2204241"
    ],
    # These packets below are dynamically generated by the library unlike previous
    # negotiation packets as past stage 5 negotiations the packets use the shared
    # secret for encryption which is different from device to device due to different
    # public keys. This is why constants are not used. But we can use constants for
    # the earlier packets which use static keys.
    "ff094000030001402257ec76586f3500c8f858e0ba047f237f4e2ed8c50d2f39ba3587e4010275bea22242936f08784271e19d67a6275ff6bb50577acec0a068": [
        "ff091b000300014822f60b45600839b2c171b33dc5790ed64ae32d"
    ],
    "ff094600030001402757ec76586f3501e8cf6185d8c4035707377af9af3a2e40b02b86e7531974f1c22440de6e43705566b77cf940280d70e86b1fa915ab5a360040237091b9": [
        "ff091b000300014827f60b45600839b2c171b33dc5790ed64ae328"
    ],
    # 4200 and 420a with the typed timestamp trailer the app sends, the
    # region typed 02 and no a5; derived from the recorded session, not recorded
    "ff09240003000f420057e9b8dfdf5f4cb54d31ac87bed31d41ecb37d5d18230d9b61c029": [],
    "ff09500003000f420a57e9b883d95ee48e5b7de48d980206577e2dafbb3d604dea3686f3011969f0db2311906d142b5730ee2bfb11e3fbbe2f82a82600c80c7e7ffe9781ec3fecc686c7b90a05edf0a9": [],
}
"""
This maps the expected commands sent by the library to what my Anker Prime 160w
charger sends in response. Its used to emulate it for testing negotiations.
"""


NEGOTIATION_RESPONSES_SOLIX: dict[str, list[str]] = {
    NEGOTIATION_COMMAND_0: ["ff090e00030001080100a1010152"],
    NEGOTIATION_COMMAND_1: [
        "ff091b00030001080300a10102a202fd00a30144a40101a50102ff"
    ],
    NEGOTIATION_COMMAND_2: [
        "ff093800030001082900a10103a2054553503332a307302e302e302e33a41041504339464530453237333030323735a506f49d8a104e0c9a"
    ],
    NEGOTIATION_COMMAND_3: ["ff090b00030001080500f2"],
    NEGOTIATION_COMMAND_4: [
        "ff094d00030001082100a140b2ade5cac4f4a0c1307e44a0e9c5363cb21e4c8485ee324c23be949fa5d5929a75e57da3207c948a0c366ca9ea1ab2cb8e57d2d046a6ebefe5d96adb5d4cb35039"
    ],
    # The command sent to the device in response to entering stage 5
    # is encrypted using the shared secret
    SOLIX_NEGOTIATION_4022: [],
}
"""
This maps the expected commands sent by the library to what my Anker Solix C1000(X)
sends in response. Its used to emulate it for testing negotiations.
"""

SOLARBANK2_CLEAR_TELEMETRY = [
    "ff09fd0003010f840513a10131a2110041504347513830463038363030333530a302015ca4020102a503020000a6050301000524a705030000061fa8050300030208a9020100aa02011fab0503f8250000ac050308020000ad02015cae020100af020100b0050360670100b10503b86e0000b205036f830200b3050345670000b402010ab5020105b602010ab7050300000000b8020101b9020100ba050328000000bb020100bc050300000000bd050300000000be050300000000bf050300000000c0110000000000000000000000000000000000c1020100c203022003c4050308020000c5020100c6020101c703023200c8050300000000c9050315",
    "ff09fd0003010f84052300000000ca050300000000cb0503da0c0000cc0503a80c0000cd0503760c0000d2020100d3050308020000d4110000000000000000000000000000000000d503020000d6110000000000000000000000000000000000d703020000d8110000000000000000000000000000000000d903020000da110000000000000000000000000000000000db03020000dc110000000000000000000000000000000000dd03020000de110000000000000000000000000000000000df03020000e0020103e1020100e2020100e3020100e4020100e5020100e6020100e7020100e8020100e9020100ea020101fe0503c6423868fb05030099",
    "ff09260003010f840533000000fc160401010101000101010101000000000000000000000080",
]
"""
A Solarbank 2 E1600 Pro's telemetry on firmware that sent it clear: one
``8405`` (fragmented, not encrypted) in three fragments. From SolixBLE issue #1.
"""

SOLARBANK2_SERIAL = "APCGQ80F08600350"
"""
The serial in ``SOLARBANK2_CLEAR_TELEMETRY``'s ``a2``.
"""